= 10장. 예외 처리

:icons: font
:Author: Byeongsoon Jang
:Email: byeongsoon94@gmail.com
:Date: 2020.09.19
:Revision: 1.0
:imagesdir: ./image


책 '이것이 자바다 - 신용권'를 학습하면서 기억해두면 좋은점을 기록한다.

여러번 보면서 놓쳤던 부분들을 체크하며, 기본에 충실한다.

{Author}<{Email}>

---

==== 예외와 예외 클래스

자바에서는 에러 이외에 예외(exception)이라고 부르는 오류가 있다.(에러는 하드웨어 오동작 또는 고장으로 인해 실행 오류가 발생하는 것)

예외란 사용자의 잘못된 조작이나 개발자의 잘못된 코딩으로 인해 발생하는 프로그램 오류이다.

예외는 발생되면 프로그램이 종료되는데 예외 처리를 통해 프로그램을 종료하지 않고 정상 실행 상태가 유지되도록 할 수 있다.

예외에는 일반 예외(Exception)과 실행 예외(Runtime Exception)이 있다.

* 일반 예외 : 컴파일 체크 예외라고도 하고, 자바 소스를 컴파일 하는 과정에서 예외 처리 코드가 필요한지 검사
** 만약 예외 처리 코드가 없다면 컴파일 오류가 발생
** RuntimeException을 상속받지 않는 클래스

* 실행 예외 : 컴파일 과정에서 예외 처리 코드를 검사하지 않는 예외
** RuntimeException을 상속받은 클래스

JVM은 프로그램을 실행하는 도중에 예외 발생 시 해당 예외 클래스로 객체를 생성한다.

모든 예외 클래스는 java.lang.Exception을 상속받는다.

==== 실행 예외

* NullPointerException

실행 예외 중에서 우리가 가장 자주 접하는 예외는 NullPointerException일 것이다.

이 예외는 객체 참조가 없는 상태, null 값을 갖는 참조 변수로 객체 접근을 했을 때 발생한다.

.NullPointerExceptionExample.java
[source, java]
----
public class NullPointerExceptionExample {
  public void static main(String[] args) {
    String name = null;
    System.out.println(name.toString()); // name은 아무 객체도 참조하고 있지 않다.
  }
}
----

프로그램에서 예외가 발생하면 에러 메시지와 함께 프로그램이 종료된다.

* ArrayIndexOutOfBoundsException

예외 이름을 보면 조금은 어떤 예외가 발생하는지 예상해 볼 수 있다.

이 예외는 배열에서 인덱스 범위를 초과 사용할 경우 발생한다.

.ArrayIndexOutOfBoundsExceptionExample.java
[source, java]
----
public class ArrayIndexOutOfBoundsExceptionExample {
  public static void main(String[] args) {
    String firstName = args[0];
    String lastName = args[1];

    System.out.println("firstName : " + args[0]);
    System.out.println("lastName : " + args[1]);
  }
}
----

위 예제에서는 프로그램 실행 시 실행 매개값을 주지 않으면 ArrayIndexOutOfBoundsException이 발생한다.

위와 같은 예외는 아래의 예제 처럼 배열 값을 사용하기 전에 배열의 길이를 미리 체크하면 예외 발생을 예방할 수 있다.

.ArrayIndexOutOfBoundsExceptionExample
[source, java]
----
public class ArrayIndexOutOfBoundsExceptionExample {
  public static void main(String[] args) {
    if(args.lenth == 2) {
      String firstName = args[0];
      String lastName = args[1];

      System.out.println("firstName : " + args[0]);
      System.out.println("lastName : " + args[1]);
    } else {
      System.out.println("[실행 방법]");
      System.out.print("java ArrayIndexOutOfBoundsExceptionExample");
      System.out.print("값1 값2");
    }
  }
}
----

* NumberFormatException

문자열로 되어 있는 데이터 값을 숫자로 변경하는 경우가 자주 발생한다.

이때 숫자로 변환될 수 없는 문자가 포함되어 있다면 NumberFormatException이 발생한다.

.NumberFormatExceptionExample.java
[source, java]
----
public class NumberFormatExceptionExample {
  public static void main(String[] agrs) {
    String age = "27";
    String birthday = "03/23";

    int value1 = Integer.parseInt(age);
    int value2 = Integer.parseInt(birthday); // NumberFormatException 발생
  }
}
----

* ClassCastException

타입 변환(Casting)은 상위 클래스와 하위 클래스 간에 발생하고 구현 클래스와 인터페이스 간에도 발생한다.

이런 관계가 아니라면 다른 클래스로 타입 변환할 수 없다.

억지로 타입 변환을 시도할 때 ClassCastException이 발생한다.

==== 예외 처리 코드

예외가 발생했을 때 프로그램의 종료를 막고, 정상 실행을 유지하도록 도와주는 것이 예외 처리 코드라고 한다.

예외 처리 코드는 try-catch-finally 블록을 이용한다.

try 블록에는 예외 발생 가능 코드가 온다. 예외가 발생하면 catch 블록으로 이동해서 예외 처리 코드가 실행된다.

예외 발생 여부와 상관없이 실행해야 되는 내용이 있다면 finally 블록을 작성해주면 된다.

try와 catch 블록에서 return문을 사용하더라도 finally 블록은 항상 실행된다.

.일반 예외 처리
====
Class.forName() 메소드는 매개값으로 주어진 클래스가 존재하면 객체를 리턴하지만 존재하지 않으면 ClassNotFoundException 예외를 발생시킨다.(ClassNotFoundException은 일반 예외)

.TryCatchFinallyExample.java
[source, java]
----
public class TryCatchFinallyExample {
  public static void main(String[] args) {
    try {
      Class clazz = Class.forName("java.lang.String2");
    } catch (ClassNotFoundException e) {
      System.out.println("클래스가 존재하지 않습니다.");
    }
  }
}
----

====

.실행 예외 처리
====
ArrayIndexOutOfBoundsException이나 NumberFormatException 같은 실행 예외는 컴파일러가 예외 처리 코드를 처리하지 않기 때문에 빨간 밑줄이 생기지 않는다.

개발자의 경험과 눈썰미로 예외 처리를 작성해야 한다.

.TryCatchFinallyRuntimeExceptionExample.java
[source, java]
----
public class TryCatchFinallyRuntimeExceptionExample {
  public static void main(String[] args) {
    String data1 = null;
    String data2 = null;

    try{
      data1 = args[0];
      data2 = args[1];
    } catch(ArrayIndexOutOfBoundsException e) {
      System.out.println("실행 매개값의 수가 부족합니다.");
      System.out.println("[실행 방법]");
      System.out.println("java TryCatchFinallyRuntimeExceptionExample num1 num2");
      return;
    }

    try {
      int value1 = Integer.parseInt(data1);
      int value2 = Integer.parseInt(data2);
      int result = value1 + value2;

      System.out.println(data1 + "+" + data2 + "=" + result);
    } catch(NumberFormatException e) {
      System.out.println("숫자로 변환할 수 없습니다.");
    } finally {
      System.out.println("다시 실행하세요");
    }
  }
}
----

====

==== 예외 종류에 따른 처리 코드

====== 다중 catch

try 블록 내부는 다양한 종류의 예외가 발생할 수 있다.

발생되는 예외별로 예외 처리 코드를 다르게 하려면 다중 catch 블록을 작성하면 된다.

[source, java]
----
try {

  // ArrayIndexOutOfBoundsException 발생

  // NumberFormatException 발생

} catch(ArrayIndexOutOfBoundsException e) {
  // 예외 처리
} catch(NumberFormatException e) {
  // 예외 처리
}
----

catch 블록이 여러 개라도 예외는 하나가 발생하면 즉시 실행을 멈추고 해당 catch 블록으로 이동하기 때문에 하나의 catch 블록만 실행된다.

====== catch 순서

다중 catch 블록을 작성할 때 주의할 점은 상위 예외 클래스가 하위 예외 클래스보다 아래쪽에 위치해야 한다.

try 블록에서 예외 발생 시 예외를 처리할 catch 블록은 위에서부터 차례대로 검색된다.

이때 상위 예외 클래스가 위에 있다면 하위 예외 클래스의 catch 블록은 실행되지 않는다.

[source, java]
----
try {

  // ArrayIndexOutOfBoundsException 발생

  // NumberFormatException 발생

} catch(Exception e) {
  // 예외 처리
} catch(ArrayIndexOutOfBoundsException e) {
  // 어떤 경우라도 이 블록은 실행되지 않는다.
}

// 수정
try {

  // ArrayIndexOutOfBoundsException 발생

  // NumberFormatException 발생

} catch(ArrayIndexOutOfBoundsException e) {
  // 예외 처리1
} catch(Exception e) {
  // 예외 처리2
}
----

====== 멀티 catch

자바 7부터 하나의 catch 블록에서 여러 개의 예외를 처리할 수 있도록 멀티 catch 기능을 추가했다.

[source, java]
----
try {

  // ArrayIndexOutOfBoundsException 또는 NumberFormatException 발생

  // NumberFormatException 발생

} catch(ArrayIndexOutOfBoundsException | NumberFormatException e) {
  // 예외 처리1
} catch(Exception e) {
  // 예외 처리2
}
----

==== 자동 리소스 닫기

자바 7에서 새로 추가된 try-with-resource를 사용하면 예외 발생 여부와 상관없이 사용했던 리소스 객체의 close() 메소드를 호출해서 안전하게 리소스를 닫는다.

[TIP]
====
리소스란 여러가지 의미가 있지만 여기서는 간단하게 데이터를 읽고 쓰는 객체라고 생각.

파일의 데이터를 읽는 FileInputStream, 객체와 파일에 쓰는 FileOutputStream은 리소스 객체
====

.try-with-resource예제
[source, java]
----
try(FileInputStream fis = new FileInputStream("file.txt")) {
  ...
} catch(IOException e) {
  ...
}
----

try-with-resource를 사용하기 위해서는 조건이 있는데, 리소스 객체는 java.lang.AutoCloseable 인터페이스를 구현하고 있어야 한다.

AutoCloseable에는 close() 메소드가 정의되어 있어서 이 메소드를 자동 호출한다.

==== 예외 떠넘기기
